---
engines:
  bandit:
    exclude_paths:
      - "tests/**"
  lizard:
    exclude_paths:
      - "tests/**"
      - "uv.lock"
  markdownlint:
    exclude_paths:
      - "CHANGELOG.md"
      - "CLAUDE.md"
  prospector:
    exclude_paths:
      - "tests/**"
  ruff:
    exclude_paths:
      - "uv.lock"
  semgrep:
    exclude_paths:
      - "tests/**"
