# Read the Docs configuration file
# Ref: https://docs.readthedocs.com/platform/stable/config-file/v2.html
version: 2
formats: all

# https://docs.readthedocs.com/platform/stable/config-file/v2.html#sphinx
sphinx:
  # Required: path to the 'conf.py' file
  configuration: docs/conf.py

# https://docs.readthedocs.com/platform/stable/config-file/v2.html#build
build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    # Custom environment setup. Only uv is required (python is already setup)
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest

    # Custom docs dependencies installation, based on uv.lock
    install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs
